*&---------------------------------------------------------------------*
*& Include Z03_S24_CUST_PACKAGE_TOP                 - Module Pool      Z03_S24_CUST_PACKAGE
*&---------------------------------------------------------------------*
*---------------------------------------------------------------------*
* TYPE Declaration
*---------------------------------------------------------------------*

* TYPE Declaration for Y03S24999_PACKGE Table
TYPES: BEGIN OF TY_PACKAGE,
             ID                 TYPE Y03S24999_PACKGE-ID,
             NAME               TYPE Y03S24999_PACKGE-NAME,
             DESCRIPTION        TYPE Y03S24999_PACKGE-DESCRIPTION,
             LINE_COLOR         TYPE LVC_T_SCOL,
       END OF TY_PACKAGE.

* TYPE Declaration for Y03S24999_PCKPRV Table
TYPES: BEGIN OF TY_PCKPRV,
             ID                 TYPE Y03S24999_PCKPRV-ID,
             PACKAGE_ID         TYPE Y03S24999_PACKGE-ID,
             PRODUCT_VARIANT_ID TYPE Y03S24999_PROVRT-ID,
             SEL                TYPE C,
             PRODUCT_ID         TYPE Y03S24999_PRODCT-ID,
             PRODUCT_NAME       TYPE Y03S24999_PRODCT-PRODUCT_NAME,
             VARIANT_CODE       TYPE Y03S24999_PROVRT-VARIANT_CODE,
             QUANTITY           TYPE Y03S24999_PCKPRV-QUANTITY,
        END OF TY_PCKPRV.

* TYPE Declaration for Y03S24999_PCKSER Table
TYPES: BEGIN OF TY_PCKSER,
             ID            TYPE Y03S24999_PCKSER-ID,
             PACKAGE_ID    TYPE Y03S24999_PACKGE-ID,
             SERVICE_ID    TYPE Y03S24999_PCKSER-ID,
             SEL           TYPE C,
             SERVICE_NAME  TYPE Y03S24999_SERVCE-NAME,
      END OF TY_PCKSER.

* TYPE Declaration for Y03S24999_PCKIMG Table
TYPES: BEGIN OF TY_PCKIMG,
            ID         TYPE Y03S24999_PCKIMG-ID,
            PACKAGE_ID TYPE Y03S24999_PCKIMG-PACKAGE_ID,
            SEL        TYPE C,
            IMAGE_URL  TYPE Y03S24999_PCKIMG-IMAGE_URL,
      END OF TY_PCKIMG.

* TYPE Declaration for Y03S24999_PRODCT Table for 0120 Product Model Dialog Box
TYPES: BEGIN OF TY_PRODUCT_0120,
            ID           TYPE Y03S24999_PRODCT-ID,
            PRODUCT_CODE TYPE Y03S24999_PRODCT-PRODUCT_CODE,
            BRAND        TYPE Y03S24999_PRODCT-BRAND,
            PRODUCT_NAME TYPE Y03S24999_PRODCT-PRODUCT_NAME,
       END OF TY_PRODUCT_0120.

* TYPE Declaration for Y03S24999_PROVRT Table for 0130 Product Model Dialog Box
TYPES: BEGIN OF TY_PROVRT_0130,
            ID            TYPE Y03S24999_PROVRT-ID,
            PRODUCT_ID    TYPE Y03S24999_PROVRT-PRODUCT_ID,
            PRODUCT_CODE  TYPE Y03S24999_PRODCT-PRODUCT_CODE,
            PRODUCT_NAME  TYPE Y03S24999_PRODCT-PRODUCT_NAME,
            VARIANT_CODE  TYPE Y03S24999_PROVRT-VARIANT_CODE,
       END OF TY_PROVRT_0130.

* TYPE Declaration for Y03S24999_PROATV Table for 0140 Product Model Dialog Box
TYPES: BEGIN OF TY_PROATV_0140,
            ID             TYPE Y03S24999_PROATV-ID,
            ATTRIBUTE_NAME TYPE Y03S24999_PROATR-ATTRIBUTE_NAME,
            VALUE          TYPE Y03S24999_PROATV-VALUE,
       END OF TY_PROATV_0140.

* TYPE Declaration for Y03S24999_SERVCE Table for 0150 Product Model Dialog Box
TYPES: BEGIN OF TY_SERVICE_0150,
            ID            TYPE Y03S24999_SERVCE-ID,
            NAME          TYPE Y03S24999_SERVCE-NAME,
            DESCRIPTION   TYPE Y03S24999_SERVCE-DESCRIPTION,
        END OF TY_SERVICE_0150.

*---------------------------------------------------------------------*
* CLASS Definition
*---------------------------------------------------------------------*
CLASS C_EVENT_RECEIVER DEFINITION.
  " The class is used to test the events raised by the cl_gui_pictureclass
  PUBLIC SECTION.
    METHODS EVENT_HANDLER_PICTURE_DBLCLICK
      FOR EVENT PICTURE_DBLCLICK OF CL_GUI_PICTURE
      IMPORTING MOUSE_POS_X MOUSE_POS_Y SENDER.
ENDCLASS.

CLASS CL_PACKAGE_ALV_HANDLER DEFINITION.
  PUBLIC SECTION.

    METHODS HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
      IMPORTING
        E_ROW_ID
        E_COLUMN_ID
        ES_ROW_NO.

ENDCLASS.

*CLASS CL_PACKAGE_PRODUCT_ALV_HANDLER DEFINITION.
*  PUBLIC SECTION.
*
*    METHODS HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
*      IMPORTING
*        E_ROW_ID
*        E_COLUMN_ID
*        ES_ROW_NO.
*
*ENDCLASS.

CLASS CL_PACKAGE_PROVRT_ALV_HANDLER DEFINITION.
  PUBLIC SECTION.

    METHODS HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
      IMPORTING
        E_ROW_ID
        E_COLUMN_ID
        ES_ROW_NO.

ENDCLASS.
*---------------------------------------------------------------------*
* DATA Declaration
*---------------------------------------------------------------------*
DATA: GV_OKCODE      TYPE SYST-UCOMM.
DATA: GV_OKCODE_0120 TYPE SYST-UCOMM.
DATA: GV_OKCODE_0130 TYPE SYST-UCOMM.
DATA: GV_OKCODE_0140 TYPE SYST-UCOMM.
DATA: GV_OKCODE_0150 TYPE SYST-UCOMM.
DATA: GV_OKCODE_0160 TYPE SYST-UCOMM.
DATA: GV_OKCODE_0170 TYPE SYST-UCOMM.
DATA: GV_PACKAGE_NAME_DUMMY TYPE Y03S24999_PACKGE-NAME.

* Internal Table Declaration for PACKAGE Table
DATA: IT_PACKAGE TYPE STANDARD TABLE OF TY_PACKAGE.

* PACKAGE ALV Table Object
DATA: O_PACKAGE_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_PACKAGE_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID,
      O_PACKAGE_HANDLER   TYPE REF TO CL_PACKAGE_ALV_HANDLER.

* Internal Table Declaration for PRODUCT_0120 Table
DATA: IT_PRODUCT_0120 TYPE STANDARD TABLE OF TY_PRODUCT_0120.

* PRODUCT_0120 ALV Table Object
DATA: O_PRODUCT_0120_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_PRODUCT_0120_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID.

* Internal Table Declaration for PROVRT_0130 Table
DATA: IT_PROVRT_0130 TYPE STANDARD TABLE OF TY_PROVRT_0130.

* PRODUCT_0130 ALV Table Object
DATA: O_PROVRT_0130_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_PROVRT_0130_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID,
      O_PROVRT_0130_HANDLER   TYPE REF TO CL_PACKAGE_PROVRT_ALV_HANDLER.

* Internal Table Declaration for PROATV_0140 Table
DATA: IT_PROATV_0140 TYPE STANDARD TABLE OF TY_PROATV_0140.

* PROATV_0140 ALV Table Object
DATA: O_PROATV_0140_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_PROATV_0140_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID.

* Internal Table Declaration for SERVICE_0150 Table
DATA: IT_SERVICE_0150 TYPE STANDARD TABLE OF TY_SERVICE_0150.

* SERVICE_0150 ALV Table Object
DATA: O_SERVICE_0150_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_SERVICE_0150_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID.

*ID of the selected package
DATA: GV_PACKAGE_ID TYPE Y03S24999_PACKGE-ID.

*Package Instance
DATA: GS_PACKAGE_DETAIL TYPE TY_PACKAGE.

*Internal table for Package Product Variant for table control
DATA: GS_PCKPRV            TYPE TY_PCKPRV.
DATA: GT_PCKPRV            TYPE STANDARD TABLE OF TY_PCKPRV WITH KEY ID PACKAGE_ID PRODUCT_VARIANT_ID.

*Internal table for Package Service for table control
DATA: GS_PCKSER            TYPE TY_PCKSER.
DATA: GT_PCKSER            TYPE STANDARD TABLE OF TY_PCKSER WITH KEY ID PACKAGE_ID SERVICE_ID.

*Internal table for Package Image for table control
DATA: GS_PCKIMG            TYPE TY_PCKIMG.
DATA: GT_PCKIMG            TYPE STANDARD TABLE OF TY_PCKIMG WITH KEY ID PACKAGE_ID.

*Table controls in Screen 0160
CONTROLS: PCKPRV_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0160.
CONTROLS: PCKSER_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0160.
CONTROLS: PCKIMG_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0160.

* Package Color Table
DATA: GT_PACKAGE_COLOR TYPE STANDARD TABLE OF LVC_S_COLO.

DATA GV_PCKIMG_URL TYPE CNDP_URL.
DATA PCKIMG_CONTROL TYPE REF TO CL_GUI_PICTURE.
DATA PCKIMG_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA PCKIMG_EVENT_RECEIVER  TYPE REF TO C_EVENT_RECEIVER.
DATA PCKIMG_EVENT_TAB TYPE CNTL_SIMPLE_EVENTS.
DATA PCKIMG_EVENT_TAB_LINE TYPE CNTL_SIMPLE_EVENT.
DATA PCKIMG_RETURN TYPE I.

* Multiline Description
DATA: PCKDES_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      PCKDES_EDITOR    TYPE REF TO CL_GUI_TEXTEDIT.

DATA: PCKDES_LINE                TYPE C LENGTH 256,
      PCKDES_TEXT_TAB            LIKE STANDARD TABLE OF PCKDES_LINE,
      PCKDES_FIELD               LIKE LINE.
*&---------------------------------------------------------------------*
*& CONSTANTS DECLARATION
*&---------------------------------------------------------------------*
CONSTANTS: G_PROG LIKE SY-REPID VALUE 'Z03_S24_CUST_PACKAGE'.

*&---------------------------------------------------------------------*
*& Selection Screen
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF SCREEN 0110 AS SUBSCREEN.
  SELECT-OPTIONS : P_PKNAME FOR GV_PACKAGE_NAME_DUMMY.
SELECTION-SCREEN END OF SCREEN 0110.
