*&---------------------------------------------------------------------*
*& Include          Z03_S24_999_CONTRACT_TOP
*&---------------------------------------------------------------------*
* TYPE Declaration for Y03S24999_CNTRCT Table
TYPES: BEGIN OF TY_CONTRACT,
         ID                   TYPE Y03S24999_CNTRCT-ID,
         QUOTATION_VERSION_ID TYPE Y03S24999_QUOVER-ID,
         CONTRACT_CODE        TYPE Y03S24999_CNTRCT-CONTRACT_CODE,
         CUSTOMER             TYPE Y03S24999_CNTRCT-CUSTOMER,
         STAFF                TYPE Y03S24999_CNTRCT-STAFF,
         STATUS               TYPE Y03S24999_CNTRCT-STATUS,
         SIGNATURE            TYPE Y03S24999_CNTRCT-SIGNATURE,
         DESCRIPTION          TYPE Y03S24999_CNTRCT-DESCRIPTION,
         SIGNED_ON            TYPE Y03S24999_CNTRCT-SIGNED_ON,
         SIGNED_AT            TYPE Y03S24999_CNTRCT-SIGNED_AT,
         CREATED_BY           TYPE Y03S24999_CNTRCT-CREATED_BY,
         CREATED_AT           TYPE Y03S24999_CNTRCT-CREATED_AT,
         CREATED_ON           TYPE Y03S24999_CNTRCT-CREATED_ON,
         UPDATED_BY           TYPE Y03S24999_CNTRCT-UPDATED_BY,
         UPDATED_AT           TYPE Y03S24999_CNTRCT-UPDATED_AT,
         UPDATED_ON           TYPE Y03S24999_CNTRCT-UPDATED_ON,
         LINE_COLOR           TYPE LVC_T_SCOL,
       END OF TY_CONTRACT.
* TYPE Declaration for CONTRACT Status Color
TYPES: BEGIN OF TY_CONTRACT_COLOR,
         STATUS TYPE Y03S24999_CNTRCT-STATUS.
         INCLUDE TYPE LVC_S_COLO.
TYPES END OF TY_CONTRACT_COLOR.
* TYPE Declaration for Contract Product Table
TYPES: BEGIN OF TY_CTRPRV,
         ID                   TYPE Y03S24999_QVSPRV-ID,
         QUOTATION_VERSION_ID TYPE Y03S24999_QUOVER-ID,
         PRODUCT_VARIANT_ID   TYPE Y03S24999_PROVRT-ID,
         SEL                  TYPE C,
         PRODUCT_ID           TYPE Y03S24999_PRODCT-ID,
         PRODUCT_NAME         TYPE Y03S24999_PRODCT-PRODUCT_NAME,
         VARIANT_CODE         TYPE Y03S24999_PROVRT-VARIANT_CODE,
         PRICE                TYPE Y03S24999_QVSPRV-PRICE,
         QUANTITY             TYPE Y03S24999_QVSPRV-QUANTITY,
         TOTAL_PRICE          TYPE Y03S24999_PROVRT-DISPLAY_PRICE,
         CREATED_BY           TYPE Y03S24999_QVSPRV-CREATED_BY,
         CREATED_AT           TYPE Y03S24999_QVSPRV-CREATED_AT,
         CREATED_ON           TYPE Y03S24999_QVSPRV-CREATED_ON,
         UPDATED_BY           TYPE Y03S24999_QVSPRV-UPDATED_BY,
         UPDATED_AT           TYPE Y03S24999_QVSPRV-UPDATED_AT,
         UPDATED_ON           TYPE Y03S24999_QVSPRV-UPDATED_ON,
       END OF TY_CTRPRV.
* TYPE Declaration for Contract Service Table
TYPES: BEGIN OF TY_CTRSER,
         ID                   TYPE Y03S24999_QVSSER-ID,
         QUOTATION_VERSION_ID TYPE Y03S24999_QUOVER-ID,
         SERVICE_ID           TYPE Y03S24999_QVSSER-ID,
         SEL                  TYPE C,
         SERVICE_NAME         TYPE Y03S24999_SERVCE-NAME,
         PRICE                TYPE Y03S24999_QVSSER-PRICE,
         CREATED_BY           TYPE Y03S24999_QVSSER-CREATED_BY,
         CREATED_AT           TYPE Y03S24999_QVSSER-CREATED_AT,
         CREATED_ON           TYPE Y03S24999_QVSSER-CREATED_ON,
         UPDATED_BY           TYPE Y03S24999_QVSSER-UPDATED_BY,
         UPDATED_AT           TYPE Y03S24999_QVSSER-UPDATED_AT,
         UPDATED_ON           TYPE Y03S24999_QVSSER-UPDATED_ON,
       END OF TY_CTRSER.
*---------------------------------------------------------------------*
* CLASS Definition
*---------------------------------------------------------------------*
CLASS CL_CONTRACT_ALV_HANDLER DEFINITION.
  PUBLIC SECTION.

    METHODS HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
      IMPORTING
        E_ROW_ID
        E_COLUMN_ID
        ES_ROW_NO.

ENDCLASS.
* CLASS C_EVENT_RECEIVER_CTR
* DEFINITION
CLASS C_EVENT_RECEIVER_CTR DEFINITION.
  " The class is used to test the events raised by the cl_gui_pictureclass
  PUBLIC SECTION.
    METHODS EVENT_HANDLER_PICTURE_DBLCLICK
      FOR EVENT PICTURE_DBLCLICK OF CL_GUI_PICTURE
      IMPORTING MOUSE_POS_X MOUSE_POS_Y SENDER.
ENDCLASS.
*---------------------------------------------------------------------*
* DATA Definition
*---------------------------------------------------------------------*
DATA: CCODE_DUMMY TYPE Y03S24999_CNTRCT-CONTRACT_CODE.
DATA: GV_CONTRACT_ID TYPE Y03S24999_CNTRCT-ID.
DATA: GV_OKCODE TYPE SYST-UCOMM.
DATA: GV_USERNAME LIKE SY-UNAME.

* Internal Table Declaration for CONTRACT Table
DATA: IT_CONTRACT TYPE STANDARD TABLE OF TY_CONTRACT.

* Status Color Table
DATA: GT_CONTRACT_COLOR TYPE STANDARD TABLE OF TY_CONTRACT_COLOR.

* ALV Table Object
DATA: O_CONTRACT_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_CONTRACT_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID,
      O_CONTRACT_HANDLER   TYPE REF TO CL_CONTRACT_ALV_HANDLER.

DATA: GS_CONTRACT_DETAIL TYPE TY_CONTRACT.

DATA: GS_CTRPRV TYPE TY_CTRPRV.
DATA: GT_CTRPRV TYPE STANDARD TABLE OF TY_CTRPRV WITH KEY ID QUOTATION_VERSION_ID PRODUCT_VARIANT_ID.

DATA: GS_CTRSER TYPE TY_CTRSER.
DATA: GT_CTRSER TYPE STANDARD TABLE OF TY_CTRSER WITH KEY ID QUOTATION_VERSION_ID SERVICE_ID.

DATA: GV_CTRPRV_TOTAL_PRICE  TYPE Y03S24999_PROVRT-DISPLAY_PRICE VALUE 0.
DATA: GV_CTRSER_TOTAL_PRICE  TYPE Y03S24999_SERVCE-DISPLAY_PRICE VALUE 0.
DATA: GV_CONTRACT_TOTAL_PRICE  TYPE Y03S24999_PROVRT-DISPLAY_PRICE VALUE 0.

DATA GV_CTRIMG_URL TYPE CNDP_URL.
DATA CTRIMG_CONTROL TYPE REF TO CL_GUI_PICTURE.
DATA CTRIMG_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA CTRIMG_EVENT_RECEIVER  TYPE REF TO C_EVENT_RECEIVER_CTR.
DATA CTRIMG_EVENT_TAB TYPE CNTL_SIMPLE_EVENTS.
DATA CTRIMG_EVENT_TAB_LINE TYPE CNTL_SIMPLE_EVENT.
DATA CTRIMG_RETURN TYPE I.

DATA: CTRDES_CONTAINER01 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      CTRDES_EDITOR01    TYPE REF TO CL_GUI_TEXTEDIT.

DATA: CTRDES_LINE01     TYPE C LENGTH 256,
      CTRDES_TEXT_TAB01 LIKE STANDARD TABLE OF CTRDES_LINE01,
      CTRDES_FIELD01    LIKE CTRDES_LINE01.

CONTROLS: CTRPRV_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0200.
CONTROLS: CTRSER_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0200.
*&---------------------------------------------------------------------*
*& Selection Screen
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF SCREEN 0110 AS SUBSCREEN.
  SELECT-OPTIONS : C_CODE FOR CCODE_DUMMY.
SELECTION-SCREEN END OF SCREEN 0110.
