*&---------------------------------------------------------------------*
*& Include          Z03_S24_999_DATA_EDIT_QUOVER
*&---------------------------------------------------------------------*
TYPES: BEGIN OF TY_QVSPRV,
         TOTAL_PRICE TYPE Y03S24999_QUOVER-TOTAL_PRICE.
TYPES: END OF TY_QVSPRV.

TYPES: BEGIN OF TY_QVSSER,
         PRICE TYPE Y03S24999_QUOVER-TOTAL_PRICE.
TYPES: END OF TY_QVSSER.

DATA: T_QUOVER TYPE STANDARD TABLE OF Y03S24999_QUOVER.
DATA: T_QVSPRV TYPE STANDARD TABLE OF TY_QVSPRV.
DATA: T_QVSSER TYPE STANDARD TABLE OF TY_QVSSER.

SELECT *
  FROM Y03S24999_QUOVER
  INTO TABLE @T_QUOVER.

IF SY-SUBRC = 0.
  LOOP AT T_QUOVER INTO DATA(S_ROW).
    CLEAR: T_QVSPRV, T_QVSSER.

    SELECT ( PRICE * QUANTITY ) AS TOTAL_PRICE
    FROM Y03S24999_QVSPRV
    WHERE IS_DELETED <> @ABAP_TRUE AND
          QUOTATION_VERSION_ID = @S_ROW-ID
    INTO TABLE @T_QVSPRV.

    SELECT PRICE
    FROM Y03S24999_QVSSER
    WHERE IS_DELETED <> @ABAP_TRUE AND
          QUOTATION_VERSION_ID = @S_ROW-ID
    INTO TABLE @T_QVSSER.

    S_ROW-TOTAL_PRICE = 0.

    LOOP AT T_QVSPRV INTO DATA(S_QVSPRV).
      S_ROW-TOTAL_PRICE += S_QVSPRV-TOTAL_PRICE.
    ENDLOOP.

    LOOP AT T_QVSSER INTO DATA(S_QVSSER).
      S_ROW-TOTAL_PRICE += S_QVSSER-PRICE.
    ENDLOOP.

    MODIFY T_QUOVER FROM S_ROW INDEX SY-TABIX.

  ENDLOOP.

  UPDATE Y03S24999_QUOVER FROM TABLE T_QUOVER.

  IF SY-SUBRC = 0.
    MESSAGE 'Modify Successfully.' TYPE 'S'.
  ELSE.
    MESSAGE 'Error updating database table' TYPE 'E'.
  ENDIF.

ELSE.
  MESSAGE 'Error: No data found' TYPE 'E'.
ENDIF.
