*&---------------------------------------------------------------------*
*& Include          Z03_S24_999__TOP
*&---------------------------------------------------------------------*
*---------------------------------------------------------------------*
* TYPE Declaration
*---------------------------------------------------------------------*
* TYPE Declaration for Y03S24999_PRODCT Table
TYPES: BEGIN OF TY_PRODUCT,
         ID           TYPE Y03S24999_PRODCT-ID,
         PRODUCT_CODE TYPE Y03S24999_PRODCT-PRODUCT_CODE,
         BRAND        TYPE Y03S24999_PRODCT-BRAND,
         PRODUCT_NAME TYPE Y03S24999_PRODCT-PRODUCT_NAME,
         PROCAT_ID    TYPE Y03S24999_PRODCT-PROCAT_ID,
         PROCAT_NAME  TYPE Y03S24999_PROCAT-NAME,
         CREATED_BY   TYPE Y03S24999_PRODCT-CREATED_BY,
         CREATED_AT   TYPE Y03S24999_PRODCT-CREATED_AT,
         CREATED_ON   TYPE Y03S24999_PRODCT-CREATED_ON,
         UPDATED_BY   TYPE Y03S24999_PRODCT-UPDATED_BY,
         UPDATED_AT   TYPE Y03S24999_PRODCT-UPDATED_AT,
         UPDATED_ON   TYPE Y03S24999_PRODCT-UPDATED_ON,
         LINE_COLOR   TYPE LVC_T_SCOL,
       END OF TY_PRODUCT.
* TYPE Declaration for Y03S24999_PROVRT Table
TYPES: BEGIN OF TY_PROVRT,
         ID            TYPE Y03S24999_PROVRT-ID,
         PRODUCT_ID    TYPE Y03S24999_PROVRT-PRODUCT_ID,
         SEL           TYPE C,
         VARIANT_CODE  TYPE Y03S24999_PROVRT-VARIANT_CODE,
         DISPLAY_PRICE TYPE Y03S24999_PROVRT-DISPLAY_PRICE,
         CREATED_BY    TYPE Y03S24999_PROVRT-CREATED_BY,
         CREATED_AT    TYPE Y03S24999_PROVRT-CREATED_AT,
         CREATED_ON    TYPE Y03S24999_PROVRT-CREATED_ON,
         UPDATED_BY    TYPE Y03S24999_PROVRT-UPDATED_BY,
         UPDATED_AT    TYPE Y03S24999_PROVRT-UPDATED_AT,
         UPDATED_ON    TYPE Y03S24999_PROVRT-UPDATED_ON,
       END OF TY_PROVRT.
*---------------------------------------------------------------------*
* DATA Declaration
*---------------------------------------------------------------------*
DATA: GV_PROCODE_DUMMY TYPE Y03S24999_PRODCT-PRODUCT_CODE.

* Product Color Table
DATA: GT_PRODUCT_COLOR TYPE STANDARD TABLE OF LVC_S_COLO.

* Internal Table Declaration for PRODUCT Table
DATA: IT_PRODUCT TYPE STANDARD TABLE OF TY_PRODUCT.

* PRODUCT ALV Table Object
DATA: O_PRODUCT_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_PRODUCT_ALV_TABLE TYPE REF TO CL_GUI_ALV_GRID.

DATA: PRODUCT_SCREEN_MODE TYPE C LENGTH 4 VALUE '0110'.
DATA: GS_PRODUCT_DETAIL_BEFORE_MOD TYPE TY_PRODUCT.
DATA: GS_PRODUCT_DETAIL TYPE TY_PRODUCT.

DATA: GV_PRODUCT_ID TYPE Y03S24999_PRODCT-ID.

DATA: GV_PRODUCT_SCREEN_MODE TYPE I.

DATA: GS_PROVRT            TYPE TY_PROVRT.
DATA: GT_PROVRT            TYPE STANDARD TABLE OF TY_PROVRT WITH KEY ID PRODUCT_ID.
DATA: GT_PROVRT_BEFORE_MOD TYPE STANDARD TABLE OF TY_PROVRT WITH KEY ID PRODUCT_ID.
DATA: GT_PROVRT_DELETED    TYPE STANDARD TABLE OF TY_PROVRT WITH KEY ID PRODUCT_ID.

CONTROLS: PROVRT_TABLE_CONTROL TYPE TABLEVIEW USING SCREEN 0119.
*&---------------------------------------------------------------------*
*& CONSTANTS DECLARATION
*&---------------------------------------------------------------------*
CONSTANTS: GC_PRODUCT_MODE_DISPLAY TYPE I VALUE 1,
           GC_PRODUCT_MODE_CREATE  TYPE I VALUE 2,
           GC_PRODUCT_MODE_CHANGE  TYPE I VALUE 3.
*&---------------------------------------------------------------------*
*& Selection Screen
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF SCREEN 0111 AS SUBSCREEN.
  SELECT-OPTIONS : P_PRCODE FOR GV_PROCODE_DUMMY.
SELECTION-SCREEN END OF SCREEN 0111.
